name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: checkout repo

      - run: sed -i "s|^\\(git clone.*--branch \\).*$|\\1v$(cat version.txt)|" docs/core-manage-asdf.md
        name: replace version in docs

      - uses: stefanzweifel/git-auto-commit-action@v4
        name: commit docs version update
        with:
          commit_message: "docs: update version in install instructions"

      - uses: GoogleCloudPlatform/release-please-action@v2
        name: create release
        with:
          release-type: simple
          bump-minor-pre-major: true
